format = """\
[î‚¶](fg:color0)\
$username\
[î‚´](fg:color0 bg:color1)\
$directory\
[î‚´](fg:color1 bg:color4)\
$git_branch\
$git_status\
[î‚´](fg:color4 bg:color3)\
$all\
$package\
$jobs\
$battery\
$time\
$cmd_duration\
$character"""

palette = "oceanic_next"

add_newline = true

[line_break]
disabled = true

[username]
show_always = true
style_user = "fg:color15 bg:color0"
style_root = "fg:color15 bg:color1"
format = '[å¿è€åŠ›]($style)'

[directory]
style = "fg:color0 bg:color1"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

[directory.substitutions]
"/home/shared" = "ğŸ–« "
# ".config" = "ğŸ”§ "
# "Projekte" = "ğŸ¨ "
# "org" = "ğŸ–‹ "
# "Dokumente" = "ğŸ“– "
# "Downloads" = "ï€™ "
# "Musik" = "ğŸœ "
# "Bilder" = "ï‘† "
# "Videos" = "ï€½ "

[git_branch]
symbol = "ï˜"
style = "fg:color0 bg:color4"
format = '[ $symbol $branch(:$remote_branch) ]($style)'

[git_status]
style = "fg:color0 bg:color4"
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
deleted = "x"
format = '[$all_status$ahead_behind ]($style)'

[aws]
symbol = "îŒ½ "
style = "fg:color15 bg:color3"
format = '[ $symbol ]($style)'

[conda]
symbol = "ï„Œ"
style = "fg:color15 bg:color3"
format = '[ $symbol ]($style)'

[dart]
symbol = "î˜"
style = "fg:color15 bg:color3"
format = '[ $symbol ]($style)'

[zig]
symbol = "âš¡"
style = "fg:color15 bg:color3"
format = '[ $symbol ]($style)'

[c]
symbol = "î˜"
style = "fg:color15 bg:color3"
format = '[ $symbol ]($style)'

[docker_context]
symbol = "ïŒˆ"
style = "fg:color15 bg:color3"
format = '[ $symbol $context]($style) $path '

[elixir]
symbol = "î‰µ"
style = "fg:color15 bg:color3"
format = '[ $symbol ]($style)'

[elm]
symbol = "î˜¬"
style = "fg:color15 bg:color3"
format = '[ $symbol ]($style)'

[golang]
symbol = "ï³‘"
style = "fg:color15 bg:color3"
format = '[ $symbol ]($style)'

[haskell]
symbol = "Î»"
style = "fg:color15 bg:color3"
format = '[ $symbol ]($style)'

[java]
symbol = "î‰–"
style = "fg:color15 bg:color3"
format = '[ $symbol ]($style)'

[julia]
symbol = "î˜¤"
style = "fg:color15 bg:color3"
format = '[ $symbol ]($style)'

[lua]
symbol = "î˜ "
style = "fg:color15 bg:color3"
format = '[ $symbol ]($style)'

[nim]
symbol = "ïš¤"
style = "fg:color15 bg:color3"
format = '[ $symbol ]($style)'

[nix_shell]
symbol = "ï‹œ"
style = "fg:color15 bg:color3"
format = '[ $symbol ]($style)'

[nodejs]
symbol = "î‰"
style = "fg:color15 bg:color3"
format = '[ $symbol ]($style)'

[perl]
symbol = "î©"
style = "fg:color15 bg:color3"
format = '[ $symbol ]($style)'

[php]
symbol = "î˜ˆ"
style = "fg:color15 bg:color3"
format = '[ $symbol ]($style)'

[python]
symbol = "î˜†"
style = "fg:color15 bg:color3"
format = '[ $symbol ]($style)'

[ruby]
symbol = "îˆ¾"
style = "fg:color15 bg:color3"
format = '[ $symbol ]($style)'

[rust]
symbol = "ğŸ¦€"
style = "fg:color15 bg:color3"
format = '[ $symbol ]($style)'

[swift]
symbol = "ï¯£"
style = "fg:color15 bg:color3"
format = '[ $symbol ]($style)'

[package]
symbol = "ï£–"
style = "fg:color15 bg:color3"
format = "[ $symbol ]($style)"
disabled = true

[cmd_duration]
min_time = 1
style = "fg:color0 bg:color7"
format = "[ $duration ]($style)"
disabled = true

[jobs]
symbol = "ïª´"
style = "fg:#CCCCCC bg:#787878"
format = "[ $symbol]($style)"

[battery]
full_symbol = "ï•¸ "
charging_symbol = "ï–ƒ "
discharging_symbol = "ï–‚ "
unknown_symbol = "ï•¼ "
empty_symbol = "ï– "
format = "[ $symbol$percentage ](fg:#CCCCCC bg:#787878)"
disabled = true

[[battery.display]]
threshold = 15
style = "bold fg:#CCCCCC"

[[battery.display]]
threshold = 50
style = "fg:#CCCCCC"

[[battery.display]]
threshold = 101
style = "bold fg:#CCCCCC"

[time]
disabled = true
time_format = "%R"
style = "bg:#787878"
format = '[ $time ](fg:#CCCCCC bg:#696969)'

[character]
#îƒ€
success_symbol = "[î‚´](fg:color3) \n [ğŸ©§](fg:color15)"
error_symbol = "[î‚´](fg:color3) \n [ğŸ© ](fg:color15)"

[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"

[palettes.oceanic_next]
color0 = "#1B2B34"
color8 = "#343D46"
color1 = "#EC5F67"
color9 = "#EC5F67"
color2 = "#99C794"
color10 = "#99C794"
color3 = "#FAC863"
color11 = "#FAC863"
color4 = "#6699CC"
color12 = "#6699CC"
color5 = "#C594C5"
color13 = "#C594C5"
color6 = "#5FB3B3"
color14 = "#5FB3B3"
color7 = "#A7ADBA"
color15 = "#D8DEE9"
