[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
decorations = "none"
dynamic_title = true
opacity = 0.9
startup_mode = "Maximized"

[window.dimensions]
columns = 82
lines = 24

[general]
live_config_reload = true
import = ["~/.config/alacritty/colors.toml", "~/.config/alacritty/fonts.toml"]

[font]
size = 17

#[window.padding]
#x = 30
#y = 30
